const fields = [
  "FlightNum",
  "DestCountry",
  "OriginWeather",
  "OriginCityName",
  "AvgTicketPrice",
  "DistanceMiles",
  "FlightDelay",
  "DestWeather",
  "Dest",
  "FlightDelayType",
  "OriginCountry",
  "dayOfWeek",
  "DistanceKilometers",
  "timestamp",
  "DestLocation",
  "DestAirportID",
  "Cancelled",
  "FlightTimeMin",
  "Origin",
  "OriginLocation",
  "DestRegion",
  "OriginAirportID",
  "OriginRegion",
  "DestCityName",
  "FlightTimeHour",
  "FlightDelayMin",
];

export default fields;
